# Generated by Django 3.2.14 on 2023-09-28 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("publish_project", "Publish Project")], max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                ("on_click", models.URLField(blank=True)),
                ("metadata_json", models.JSONField(blank=True)),
                (
                    "reciever_user_id",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
