# Generated by Django 3.2.14 on 2023-10-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="metadata_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="on_click",
            field=models.URLField(blank=True, null=True),
        ),
    ]
