# Generated by Django 3.2.14 on 2023-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification_seen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="seen",
        ),
        migrations.AddField(
            model_name="notification",
            name="seen_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
