version: "3.8"

services:
  db:
    restart: always
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=main"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  redis:
    container_name: redis
    image: "redis"
    ports:
      - 6379:6379

  celery:
    container_name: celery-default
    restart: always
    build: ./backend
    command: celery -A shoonya_backend.celery worker -Q default --concurrency=2 --loglevel=info
    volumes:
      - ./backend/:/usr/src/backend/
    depends_on:
      - db
      - redis
      - web

  # This is the additional queue which contains the low-priority celery tasks. We can adjust the concurrency and workers alloted to this container.
  celery2:
    container_name: celery-low-priority
    restart: always
    build: ./backend
    command: celery -A shoonya_backend.celery worker -Q functions --concurrency=2 --loglevel=info
    volumes:
      - ./backend/:/usr/src/backend/
    depends_on:
      - db
      - redis
      - web

  # Celery beats - for scheduling daily e-mails
  celery-beat:
    build: ./backend
    command: celery -A shoonya_backend.celery beat --loglevel=info
    volumes:
      - ./backend/:/usr/src/backend
    depends_on:
      - db
      - redis
      - web

  flower:
    container_name: flower
    restart: always
    build: ./backend
    command: celery -A shoonya_backend.celery flower --conf="./usr/src/backend/shoonya_backend/flowerconfig.py" --basic-auth="${FLOWER_USERNAME}:${FLOWER_PASSWORD}"
    ports:
      - "5555:5555"
    volumes:
      - ./backend/:/usr/src/backend/
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
