version: '3.3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_vol:/elasticsearch_data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.14.0
    hostname: shoonya_dev_logger
    volumes:
      - ./logstash_dev.conf:/usr/share/logstash/pipeline/logstash.conf
      - logs_vol:/logs
    extra_hosts:
      - "elasticsearch:elasticsearch"
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

volumes:
  elasticsearch_vol:
  logs_vol:

networks:
  shoonya_backend:
    external: true