# Generated by Django 3.1.14 on 2022-03-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_auto_20220317_0924"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="variable_parameters",
            field=models.JSONField(
                null=True, verbose_name="variable parameters for project"
            ),
        ),
    ]
