# Generated by Django 3.1.14 on 2022-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_project_variable_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="data_type",
            field=models.JSONField(
                blank=True, null=True, verbose_name="data type in project xml"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="expert_instruction",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="filter_string",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="label_config",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="XML Template Config",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sampling_parameters_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="sampling parameters json"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="variable_parameters",
            field=models.JSONField(
                blank=True, null=True, verbose_name="variable parameters for project"
            ),
        ),
    ]
