# Generated by Django 3.1.14 on 2022-03-24 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_auto_20220324_0755"),
        ("projects", "0009_auto_20220323_1429"),
    ]

    operations = []
