# Generated by Django 3.1.14 on 2022-03-28 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_merge_20220324_0815"),
        ("projects", "0007_auto_20220320_0729"),
    ]

    operations = []
