# Generated by Django 3.1.14 on 2022-03-28 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_merge_20220328_0340"),
        ("projects", "0013_auto_20220325_0625"),
    ]

    operations = []
