# Generated by Django 3.1.14 on 2022-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_auto_20220404_0603"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="required_annotators_per_task",
            field=models.IntegerField(
                default=1, verbose_name="required_annotators_per_task"
            ),
        ),
    ]
