# Generated by Django 3.1.14 on 2022-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataset", "0021_datasetbase_parent_data"),
        ("projects", "0018_auto_20220404_0604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dataset_id",
            field=models.ManyToManyField(
                blank=True,
                related_name="project_dataset_instances",
                to="dataset.DatasetInstance",
            ),
        ),
    ]
