# Generated by Django 3.1.14 on 2022-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_auto_20220430_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("MonolingualTranslation", "MonolingualTranslation"),
                    ("TranslationEditing", "TranslationEditing"),
                    ("ContextualTranslationEditing", "ContextualTranslationEditing"),
                    ("OCRAnnotation", "OCRAnnotation"),
                    ("MonolingualCollection", "MonolingualCollection"),
                    ("SentenceSplitting", "SentenceSplitting"),
                ],
                max_length=100,
            ),
        ),
    ]
