# Generated by Django 3.1.14 on 2022-05-02 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_auto_20220329_1309"),
        ("dataset", "0023_auto_20220502_1329"),
        ("workspaces", "0008_auto_20220426_0850"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0020_auto_20220501_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.CharField(
                blank=True, help_text="Colour", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                help_text="Project Created By",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="data_type",
            field=models.JSONField(
                blank=True,
                help_text="Data Type in the Project XML",
                null=True,
                verbose_name="data type in project xml",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="dataset_id",
            field=models.ManyToManyField(
                blank=True,
                help_text="Dataset Instances that are available for project creation",
                related_name="project_dataset_instances",
                to="dataset.DatasetInstance",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, help_text="Project Description", max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="expert_instruction",
            field=models.TextField(
                blank=True, help_text="Expert Instruction", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="filter_string",
            field=models.CharField(
                blank=True,
                help_text="Filter string for filtering data for project",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a project is archieved or not.",
                verbose_name="project_is_archived",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether a project is published or not.",
                verbose_name="project_is_published",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="label_config",
            field=models.CharField(
                blank=True,
                help_text="Label Studio Config XML to be used to show annotation task UI",
                max_length=1000,
                null=True,
                verbose_name="XML Template Config",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_json",
            field=models.JSONField(
                blank=True,
                help_text="Metadata for project",
                null=True,
                verbose_name="metadata json",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization_id",
            field=models.ForeignKey(
                help_text="Organization to which the Project belongs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_mode",
            field=models.CharField(
                choices=[("Collection", "Collection"), ("Annotation", "Annotation")],
                help_text="Mode of the Project - Annotation or Collection",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("MonolingualTranslation", "MonolingualTranslation"),
                    ("TranslationEditing", "TranslationEditing"),
                    ("ContextualTranslationEditing", "ContextualTranslationEditing"),
                    ("OCRAnnotation", "OCRAnnotation"),
                    ("MonolingualCollection", "MonolingualCollection"),
                    ("SentenceSplitting", "SentenceSplitting"),
                ],
                help_text="Project Type indicating the annotation task",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="required_annotators_per_task",
            field=models.IntegerField(
                default=1,
                help_text="No. of annotators required for each task",
                verbose_name="required_annotators_per_task",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sampling_mode",
            field=models.CharField(
                choices=[("r", "Random"), ("b", "Batch"), ("f", "Full")],
                default="f",
                help_text="Sampling Mode of the dataset for the project - Random, Batch or Full",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sampling_parameters_json",
            field=models.JSONField(
                blank=True,
                help_text="Sampling parameters for the sampling mode - percentage for random and batch number and size for batch",
                null=True,
                verbose_name="sampling parameters json",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="show_instruction",
            field=models.BooleanField(
                default=False,
                help_text="Show Instruction to Annotator",
                verbose_name="show_instruction_to_annotator",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="show_predictions_to_annotator",
            field=models.BooleanField(
                default=False,
                help_text="Show Annotation predictions to annotator",
                verbose_name="annotator_can_see_model_predictions",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="show_skip_button",
            field=models.BooleanField(
                default=False,
                help_text="Button to Skip the Project",
                verbose_name="annotator_can_skip_project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(help_text="Project Title", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                help_text="Project Users",
                related_name="project_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="variable_parameters",
            field=models.JSONField(
                blank=True,
                help_text="Variable parameters specific for each project type",
                null=True,
                verbose_name="variable parameters for project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workspace_id",
            field=models.ForeignKey(
                help_text="Workspace to which the Project belongs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspaces.workspace",
            ),
        ),
    ]
