# Generated by Django 3.1.14 on 2022-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20220516_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_pending_tasks_per_user',
            field=models.IntegerField(default=30, help_text='Maximum no. of tasks assigned to a user which are at unlabeled stage, as a threshold for pulling new tasks', verbose_name='max_pending_tasks_per_user'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_pull_count_per_batch',
            field=models.IntegerField(default=10, help_text='Maximum no. of new tasks that can be assigned to a user at once', verbose_name='tasks_pull_count_per_batch'),
        ),
    ]
