# Generated by Django 3.1.14 on 2022-06-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_auto_20220516_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="label_config",
            field=models.TextField(
                blank=True,
                help_text="Label Studio Config XML to be used to show annotation task UI",
                null=True,
                verbose_name="XML Template Config",
            ),
        ),
    ]
