# Generated by Django 4.0.4 on 2022-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_frozen_users_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='src_language',
            field=models.CharField(blank=True, choices=[('assamese', 'Assamese'), ('bodo', 'Bodo'), ('bengali', 'Bengali'), ('dogri', 'Dogri'), ('gujrati', 'Gujrati'), ('kannada', 'Kannada'), ('kashmiri', 'Kashmiri'), ('konkani', 'Konkani'), ('maithili', 'Maithili'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('nepali', 'Nepali'), ('odia', 'Odia'), ('others', 'Others'), ('punjabi', 'Punjabi'), ('sanskrit', 'Sanskrit'), ('santali', 'Santali'), ('sindhi', 'Sindhi'), ('tamil', 'Tamil'), ('telgu', 'Telgu'), ('urdu', 'Urdu')], help_text='Source language of the project', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tgt_language',
            field=models.CharField(blank=True, choices=[('assamese', 'Assamese'), ('bodo', 'Bodo'), ('bengali', 'Bengali'), ('dogri', 'Dogri'), ('gujrati', 'Gujrati'), ('kannada', 'Kannada'), ('kashmiri', 'Kashmiri'), ('konkani', 'Konkani'), ('maithili', 'Maithili'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('nepali', 'Nepali'), ('odia', 'Odia'), ('others', 'Others'), ('punjabi', 'Punjabi'), ('sanskrit', 'Sanskrit'), ('santali', 'Santali'), ('sindhi', 'Sindhi'), ('tamil', 'Tamil'), ('telgu', 'Telgu'), ('urdu', 'Urdu')], help_text='Target language of the project', max_length=50, null=True),
        ),
    ]
