# Generated by Django 3.1.14 on 2022-06-27 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0027_project_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enable_task_reviews",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the annotations need to be reviewed",
                verbose_name="enable_task_reviews",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="annotation_reviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Project Annotation Reviewers",
                related_name="review_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
