# Generated by Django 3.2.13 on 2022-07-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_id'),
        ('projects', '0026_alter_project_src_language_and_more'),
    ]

    operations = [
    ]
