# Generated by Django 3.1.14 on 2022-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_auto_20220627_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttaskrequestlock",
            name="lock_context",
            field=models.CharField(
                choices=[
                    ("annotation_task_pull_lock", "annotation_lock"),
                    ("review_task_pull_lock", "review_lock"),
                ],
                default="annotation_task_pull_lock",
                max_length=50,
                verbose_name="lock_context",
            ),
        ),
    ]
