# Generated by Django 3.2.13 on 2022-07-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_merge_20220705_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskrequestlock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
