# Generated by Django 3.2.13 on 2022-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_project_created_at'),
        ('projects', '0028_alter_projecttaskrequestlock_id'),
    ]

    operations = [
    ]
