# Generated by Django 3.2.13 on 2022-07-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projecttaskrequestlock_lock_context'),
        ('projects', '0029_merge_20220705_1235'),
    ]

    operations = [
    ]
