# Generated by Django 3.1.14 on 2022-08-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20220722_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='annotators',
        ),
    ]
