# Generated by Django 3.2.14 on 2022-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_auto_20220930_0451"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("MonolingualTranslation", "MonolingualTranslation"),
                    ("TranslationEditing", "TranslationEditing"),
                    (
                        "SemanticTextualSimilarity_Scale5",
                        "SemanticTextualSimilarity_Scale5",
                    ),
                    ("ContextualTranslationEditing", "ContextualTranslationEditing"),
                    ("OCRAnnotation", "OCRAnnotation"),
                    ("MonolingualCollection", "MonolingualCollection"),
                    ("SentenceSplitting", "SentenceSplitting"),
                    (
                        "ContextualSentenceVerification",
                        "ContextualSentenceVerification",
                    ),
                    ("ConversationTranslation", "ConversationTranslation"),
                    (
                        "ConversationTranslationEditing",
                        "ConversationTranslationEditing",
                    ),
                    (
                        "SingleSpeakerAudioTranscriptionEditing",
                        "SingleSpeakerAudioTranscriptionEditing",
                    ),
                ],
                help_text="Project Type indicating the annotation task",
                max_length=100,
            ),
        ),
    ]
