# Generated by Django 3.2.14 on 2022-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0032_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="Project published at", null=True
            ),
        ),
    ]
