# Generated by Django 3.2.14 on 2023-03-13 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0040_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="k_value",
            field=models.IntegerField(
                default=100,
                help_text="This will be used to pull k percent of tasks in a project for super-check",
                verbose_name="Superchecking K% Value",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_stage",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Annotation Only"),
                    (2, "Review Enabled"),
                    (3, "Supercheck Enabled"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="review_supercheckers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Project Review Super Checkers",
                related_name="supercheck_reviewed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="revision_loop_count",
            field=models.IntegerField(
                default=3,
                help_text="This will be used to keep track of the rejected/ reviewed-back loop count in Super check.",
                verbose_name="revision loop count",
            ),
        ),
    ]
