# Generated by Django 3.2.14 on 2023-03-13 13:15

from django.db import migrations
from projects.models import Project,REVIEW_STAGE

def populate_project_stage(apps,schema_editor):
    projects=Project.objects.all()
    projects_list=[]
    for project in projects:
        if project.enable_task_reviews:
            setattr(project,"project_stage",REVIEW_STAGE)
            projects_list.append(project)
    
    Project.objects.bulk_update(projects_list,["project_stage"],512)



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20230313_1307'),
    ]

    operations = [
        migrations.RunPython(populate_project_stage),
    ]
