# Generated by Django 3.2.14 on 2023-03-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_populate_project_stage_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='enable_task_reviews',
        ),
    ]
