# Generated by Django 3.2.14 on 2023-03-13 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0041_auto_20230313_1307"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="enable_task_reviews",
        ),
    ]
