# Generated by Django 3.2.14 on 2023-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0043_remove_project_enable_task_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttaskrequestlock",
            name="lock_context",
            field=models.CharField(
                choices=[
                    ("annotation_task_pull_lock", "annotation_lock"),
                    ("review_task_pull_lock", "review_lock"),
                    ("supercheck_task_pull_lock", "supercheck_lock"),
                ],
                default="annotation_task_pull_lock",
                max_length=50,
                verbose_name="lock_context",
            ),
        ),
    ]
