# Generated by Django 3.2.14 on 2024-01-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0051_alter_project_project_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_mode",
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("ModelOutputEvaluation", "ModelOutputEvaluation")],
                help_text="Project Type indicating the annotation task",
                max_length=100,
            ),
        ),
    ]
