# Generated by Django 3.2.14 on 2024-01-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0052_auto_20240101_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("ModelOutputEvaluation", "ModelOutputEvaluation"),
                    ("Instruction Driven Chat", "Instruction Driven Chat"),
                ],
                help_text="Project Type indicating the annotation task",
                max_length=100,
            ),
        ),
    ]
