# Generated by Django 3.2.14 on 2026-04-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0052_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('MonolingualTranslation', 'MonolingualTranslation'), ('TranslationEditing', 'TranslationEditing'), ('SemanticTextualSimilarity_Scale5', 'SemanticTextualSimilarity_Scale5'), ('ContextualTranslationEditing', 'ContextualTranslationEditing'), ('OCRTranscription', 'OCRTranscription'), ('OCRTextlineSegmentation', 'OCRTextlineSegmentation'), ('OCRTableEditing', 'OCRTableEditing'), ('OCRTranscriptionEditing', 'OCRTranscriptionEditing'), ('OCRSegmentCategorization', 'OCRSegmentCategorization'), ('OCRSegmentCategorizationEditing', 'OCRSegmentCategorizationEditing'), ('MonolingualCollection', 'MonolingualCollection'), ('SentenceSplitting', 'SentenceSplitting'), ('ContextualSentenceVerification', 'ContextualSentenceVerification'), ('ContextualSentenceVerificationAndDomainClassification', 'ContextualSentenceVerificationAndDomainClassification'), ('ConversationTranslation', 'ConversationTranslation'), ('ConversationTranslationEditing', 'ConversationTranslationEditing'), ('ConversationVerification', 'ConversationVerification'), ('AudioTranscription', 'AudioTranscription'), ('AudioSegmentation', 'AudioSegmentation'), ('AudioTranscriptionEditing', 'AudioTranscriptionEditing'), ('AcousticNormalisedTranscriptionEditing', 'AcousticNormalisedTranscriptionEditing')], help_text='Project Type indicating the annotation task', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='projectbookmark',
            index=models.Index(fields=['user', '-bookmarked_at'], name='projects_pr_user_id_17a45a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectbookmark',
            unique_together={('user', 'project')},
        ),
    ]
