# Generated by Django 3.2.14 on 2024-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0055_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_password",
            field=models.CharField(
                blank=True,
                help_text="Password for the Project",
                max_length=128,
                null=True,
            ),
        ),
    ]
