# Generated by Django 3.2.14 on 2024-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0055_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_pull_count_per_user",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum number of tasks that can be assigned to a user. Default is -1, which means all tasks can be assigned",
                verbose_name="max pull count per user",
            ),
        ),
    ]
