# Generated by Django 3.2.14 on 2024-07-01 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0056_project_max_pull_count_per_user"),
        ("projects", "0056_project_project_password"),
    ]

    operations = []
