# Generated by Django 3.2.14 on 2024-07-01 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0057_merge_20240701_0520"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="max_pull_count_per_user",
            new_name="max_tasks_per_user",
        ),
    ]
