# Generated by Django 3.2.12 on 2022-02-14 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="invite_code",
            field=models.CharField(
                max_length=256, null=True, unique=True, verbose_name="invite_code"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
    ]
