# Generated by Django 3.1.14 on 2022-03-24 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_auto_20220319_0907"),
        ("organizations", "0003_auto_20220317_0924"),
    ]

    operations = []
