# Generated by Django 3.1.14 on 2022-03-28 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_merge_20220328_0340"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invite",
            name="users",
        ),
        migrations.AddField(
            model_name="invite",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
