# Generated by Django 3.1.14 on 2022-03-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_auto_20220328_0503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_oganization",
                to="organizations.organization",
                verbose_name="organization",
            ),
        ),
    ]
