# Generated by Django 3.2.14 on 2024-07-31 10:12

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_auto_20220930_0451"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="permission_json",
            field=models.JSONField(
                blank=True,
                default=organizations.models.default_permissions,
                help_text="Permissions for user role",
                null=True,
                verbose_name="permission json",
            ),
        ),
    ]
