# Generated by Django 3.1.14 on 2022-03-24 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_auto_20220320_0635"),
        ("workspaces", "0002_auto_20220317_0924"),
    ]

    operations = []
