# Generated by Django 3.1.14 on 2022-03-24 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_auto_20220319_0907"),
        ("workspaces", "0004_merge_20220324_0642"),
    ]

    operations = []
