# Generated by Django 3.1.14 on 2022-05-16 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0008_auto_20220426_0539"),
        ("workspaces", "0008_auto_20220426_0850"),
    ]

    operations = []
