# Generated by Django 3.1.14 on 2022-08-05 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0010_workspace_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="users",
            new_name="members",
        ),
    ]
