# Generated by Django 3.2.14 on 2022-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0011_auto_20220805_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
