# Generated by Django 3.2.13 on 2022-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_workspace_created_at'),
        ('workspaces', '0012_alter_workspace_id'),
    ]

    operations = [
    ]
