# Generated by Django 3.2.13 on 2022-08-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_auto_20220805_0940'),
        ('workspaces', '0013_merge_20220705_1235'),
    ]

    operations = [
    ]
