# Generated by Django 3.2.14 on 2023-07-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0013_workspace_frozen_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="public_analytics",
            field=models.BooleanField(
                default=True,
                help_text="States whether a workspace needs to be added for analytics or not.",
                verbose_name="public_analytics",
            ),
        ),
    ]
