# Generated by Django 3.2.14 on 2024-01-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0014_workspace_public_analytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="guest_workspace",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the workspace is for guest users.",
                verbose_name="guest_workspace",
            ),
        ),
    ]
