# Generated by Django 3.2.14 on 2024-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0015_workspace_guest_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="workspace_password",
            field=models.CharField(
                blank=True,
                help_text="Password for accessing the workspace.",
                max_length=128,
                null=True,
                verbose_name="workspace_password",
            ),
        ),
    ]
