# Generated by Django 3.2.14 on 2024-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0016_workspace_workspace_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="guest_workspace",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the workspace is for guest-users.",
                verbose_name="guest_workspace",
            ),
        ),
    ]
