# Generated by Django 3.2.12 on 2022-02-28 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='task_id')),
                ('meta', models.TextField(blank=True, null=True)),
                ('domain_type', models.CharField(choices=[('monolingual', 'Monolingual'), ('speechCollection', 'Speech Collection'), ('speechRecognition', 'Speech Recognition'), ('translation', 'Translation'), ('ocr', 'OCR'), ('video', 'Video'), ('videoChunk', 'Video Chunk')], default='monolingual', max_length=100, verbose_name='dataset_domain_type')),
                ('correct_annotation', models.TextField()),
                ('task_status', models.CharField(choices=[('UnLabel', 'unlabelled'), ('Label', 'labelled'), ('Skip', 'skipped'), ('Accept', 'accepted'), ('Reject', 'rejected')], default='UnLabel', max_length=100)),
                ('annotation_users', models.ManyToManyField(related_name='annotation_users', to=settings.AUTH_USER_MODEL)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataset.datasetinstance', verbose_name='dataset_data_id')),
                ('review_user', models.ManyToManyField(related_name='review_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(verbose_name='result_json')),
                ('parent_annotation', models.TextField()),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
