# Generated by Django 3.1.14 on 2022-03-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_auto_20220318_0807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="correct_annotation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tasks.annotation",
            ),
        ),
    ]
