# Generated by Django 3.1.14 on 2022-03-23 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_auto_20220323_0949"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="data_id",
            new_name="input_data",
        ),
    ]
