# Generated by Django 3.1.14 on 2022-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_auto_20220329_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="metadata_json",
            field=models.JSONField(blank=True, null=True, verbose_name="metadata json"),
        ),
    ]
