# Generated by Django 3.1.14 on 2022-04-30 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_auto_20220429_0643"),
        ("tasks", "0017_auto_20220411_0907"),
    ]

    operations = []
