# Generated by Django 3.1.14 on 2022-04-30 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0020_merge_20220430_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="annotation_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="annotation_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="annotation_users",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="review_user",
            field=models.ManyToManyField(
                blank=True,
                related_name="review_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="review_users",
            ),
        ),
    ]
