# Generated by Django 3.1.14 on 2022-05-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20220502_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='lead_time',
        ),
    ]
