# Generated by Django 3.1.14 on 2022-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_remove_annotation_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='lead_time',
            field=models.FloatField(default=0.0, help_text='How much time it took to annotate the task', verbose_name='annotation_lead_time'),
        ),
    ]
