# Generated by Django 3.1.14 on 2022-05-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0024_auto_20220518_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='review_user',
        ),
        migrations.AddField(
            model_name='task',
            name='review_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_users', to=settings.AUTH_USER_MODEL, verbose_name='review_users'),
        ),
    ]
