# Generated by Django 4.0.5 on 2022-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20220518_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
