# Generated by Django 3.1.14 on 2022-05-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0024_auto_20220518_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='review_user',
        ),
        migrations.AddField(
            model_name='task',
            name='review_user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_users', to='users.user', verbose_name='review_users'),
            preserve_default=False,
        ),
    ]
