# Generated by Django 3.1.14 on 2022-05-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220525_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reviewable',
            field=models.BooleanField(default=False),
        ),
    ]
