# Generated by Django 3.1.14 on 2022-05-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220525_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='parent_annotation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.annotation', verbose_name='annotation_parent_annotation'),
        ),
    ]
