# Generated by Django 3.1.14 on 2022-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_annotation_parent_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('unlabeled', 'unlabeled'), ('labeled', 'labeled'), ('skipped', 'skipped'), ('accepted', 'accepted'), ('accepted_with_changes', 'accepted_with_changes'), ('freezed', 'freezed'), ('rejected', 'rejected')], default='unlabeled', max_length=100, verbose_name='task_status'),
        ),
    ]
