# Generated by Django 4.0.4 on 2022-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0026_annotation_notes_alter_tasklock_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="annotation_notes"
            ),
        ),
    ]
