# Generated by Django 3.1.14 on 2022-05-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0027_auto_20220527_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='parent_annotation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.annotation', verbose_name='parent_annotation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='review_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='review_user'),
        ),
    ]
