# Generated by Django 3.1.14 on 2022-06-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20220617_0730'),
        ('tasks', '0028_auto_20220617_0834'),
    ]

    operations = [
    ]
