# Generated by Django 3.2.13 on 2022-07-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_tasklock_id'),
        ('tasks', '0028_auto_20220617_0730'),
    ]

    operations = [
    ]
