# Generated by Django 4.0.5 on 2022-07-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_merge_20220624_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
