# Generated by Django 3.2.13 on 2022-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_merge_0027_alter_tasklock_id_0028_auto_20220617_0730'),
        ('tasks', '0029_merge_20220624_1106'),
    ]

    operations = [
    ]
