# Generated by Django 3.1.14 on 2022-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20220707_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('unlabeled', 'unlabeled'), ('labeled', 'labeled'), ('skipped', 'skipped'), ('accepted', 'accepted'), ('accepted_with_changes', 'accepted_with_changes'), ('freezed', 'freezed'), ('revise', 'revise'), ('draft', 'draft')], default='unlabeled', max_length=100, verbose_name='task_status'),
        ),
    ]
