# Generated by Django 3.2.13 on 2022-07-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20220707_0959'),
        ('tasks', '0030_merge_20220705_1235'),
    ]

    operations = [
    ]
