# Generated by Django 3.1.14 on 2022-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20220707_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_status',
            field=models.CharField(choices=[('unlabeled', 'unlabeled'), ('labeled', 'labeled'), ('skipped', 'skipped'), ('freezed', 'freezed'), ('draft', 'draft')], default='unlabeled', max_length=100, verbose_name='task_status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('skipped', 'skipped'), ('accepted', 'accepted'), ('accepted_with_changes', 'accepted_with_changes'), ('freezed', 'freezed'), ('rejected', 'rejected'), ('draft', 'draft')], default='incomplete', max_length=100, verbose_name='task_status'),
        ),
    ]
