# Generated by Django 3.1.14 on 2022-08-22 10:55

from django.db import migrations, models
from projects.utils import no_of_words


def add_word_count(apps, schema_editor):
    tasks = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    taskobj = tasks.objects.using(db_alias).all()
    for tas in taskobj:
        proj_type = tas.project_id.project_type
        project_type_lower = proj_type.lower()
        is_translation_project = True if "translation" in project_type_lower else False
        if is_translation_project:
            try:
                tas.data["word_count"] = no_of_words(tas.data["input_text"])
            except TypeError:
                pass
            except:
                tas.data["word_count"] = 0
            tas.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0031_auto_20220812_0936"),
    ]

    operations = [
        migrations.RunPython(add_word_count),
    ]
