# Generated by Django 3.1.14 on 2022-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_delete_tasklock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('unlabeled', 'unlabeled'), ('labeled', 'labeled'), ('skipped', 'skipped'), ('accepted', 'accepted'), ('accepted_with_changes', 'accepted_with_changes'), ('freezed', 'freezed'), ('to_be_revised', 'to_be_revised'), ('draft', 'draft'), ('exported', 'exported')], default='unlabeled', max_length=100, verbose_name='task_status'),
        ),
    ]
