# Generated by Django 3.2.16 on 2023-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_auto_20230127_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_status',
            field=models.CharField(choices=[('unlabeled', 'unlabeled'), ('labeled', 'labeled'), ('skipped', 'skipped'), ('draft', 'draft'), ('unreviewed', 'unreviewed'), ('accepted', 'accepted'), ('to_be_revis>
        ),
    ]
