# Generated by Django 3.2.14 on 2022-12-14 10:26


from django.db import migrations, models
from projects.utils import no_of_words
from dataset.models import DatasetInstance
from dataset import models as dataset_models


def add_word_count(apps, schema_editor):
    tasks = apps.get_model("tasks", "Task")
    db_alias = schema_editor.connection.alias
    taskobj = tasks.objects.using(db_alias).all()
    for tas in taskobj:
        try:
            if "word_count" in tas.data.keys():
                pass
            else:
                db_object_id = tas.input_data.id
                data_object = dataset_models.DatasetBase.objects.get(pk=db_object_id)
                insta_id = data_object.instance_id_id
                dsi = DatasetInstance.objects.filter(instance_id=insta_id)
                dataset_type1 = dsi[0].dataset_type

                if dataset_type1 == "TranslationPair":
                    try:
                        tas.data["word_count"] = no_of_words(tas.data["input_text"])
                    except TypeError:
                        pass
                    except:
                        tas.data["word_count"] = 0
                    tas.save()
        except AttributeError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0036_auto_20221116_0541"),
    ]

    operations = [
        migrations.RunPython(add_word_count),
    ]
