# Generated by Django 3.2.14 on 2022-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0037_auto_20221214_1026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("incomplete", "incomplete"),
                    ("annotated", "annotated"),
                    ("reviewed", "reviewed"),
                    ("Exported", "Exported"),
                    ("freezed", "freezed"),
                ],
                default="incomplete",
                max_length=100,
                verbose_name="task_status",
            ),
        ),
    ]
