# Generated by Django 3.2.14 on 2023-03-16 05:09

from django.db import migrations
from tasks.models import Annotation, REVIEWER_ANNOTATION


def populate_annotation_type(apps, schema_editor):
    review_annotations = Annotation.objects.filter(parent_annotation_id__isnull=False)
    review_annotations_list = []
    for annotation in review_annotations:
        setattr(annotation, "annotation_type", REVIEWER_ANNOTATION)
        review_annotations_list.append(annotation)

    Annotation.objects.bulk_update(review_annotations_list, ["annotation_type"], 512)


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0039_annotation_annotation_type"),
    ]

    operations = [
        migrations.RunPython(populate_annotation_type),
    ]
