# Generated by Django 3.2.14 on 2022-12-26 08:07

from django.db import migrations, models
from django.db.models import Q
from tasks.models import Annotation


def annotation_status_to_be_revised_implementation(apps, schema_editor):
    annotations = apps.get_model("tasks", "Annotation")
    db_alias = schema_editor.connection.alias
    to_be_revised_annotations = annotations.objects.using(db_alias).filter(
        parent_annotation__isnull=False, annotation_status="to_be_revised"
    )

    for ann in to_be_revised_annotations:
        parent = ann.parent_annotation
        parent.annotation_status = "to_be_revised"
        parent.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0039_alter_task_task_status"),
    ]

    operations = [
        migrations.RunPython(annotation_status_to_be_revised_implementation),
    ]
