# Generated by Django 3.2.14 on 2023-03-23 05:59

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0039_annotation_annotation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="revision_loop_count",
            field=models.JSONField(
                default=tasks.models.default_revision_loop_count_value,
                help_text="Has the revision_loop_count of both supercheck and review",
                verbose_name="revision_loop_count",
            ),
        ),
    ]
