# Generated by Django 3.2.14 on 2023-03-24 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0041_task_revision_loop_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="super_check_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="super_check_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="supercheck_user",
            ),
        ),
    ]
