# Generated by Django 3.2.14 on 2023-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0043_annotation_supercheck_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="annotation_source",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Manual Annotation"), (1, "Automatic Annotation")],
                default=0,
            ),
        ),
    ]
