# Generated by Django 3.2.14 on 2023-07-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0044_annotation_annotation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="annotated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="annotation_annotated_at"
            ),
        ),
    ]
