# Generated by Django 3.2.14 on 2023-07-27 07:28

from django.db import migrations


def update_annotated_at(apps, schema_editor):
    Annotation = apps.get_model("tasks", "Annotation")
    objs = []
    for annotation in Annotation.objects.all().iterator():
        if annotation.annotated_at is None:
            annotation.annotated_at = annotation.updated_at
            objs.append(annotation)

    Annotation.objects.bulk_update(objs, ["annotated_at"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0045_annotation_annotated_at"),
    ]

    operations = [
        migrations.RunPython(update_annotated_at),
    ]
