# Generated by Django 3.2.14 on 2023-07-27 07:28

from django.db import migrations
from django.core.paginator import Paginator


def update_annotated_at(apps, schema_editor):
    Annotation = apps.get_model("tasks", "Annotation")
    queryset = Annotation.objects.all().order_by("id")
    paginator = Paginator(queryset, 10000)

    for page_number in paginator.page_range:
        chunk = paginator.page(page_number)
        objs = []

        for annotation in chunk.object_list:
            if annotation.annotated_at is None:
                annotation.annotated_at = annotation.updated_at
                objs.append(annotation)

        Annotation.objects.bulk_update(objs, ["annotated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0045_annotation_annotated_at"),
    ]

    operations = [
        migrations.RunPython(update_annotated_at),
    ]
