# Generated by Django 3.2.14 on 2023-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0046_auto_20230727_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when the annotation was first labeled/accepted/validated",
                null=True,
                verbose_name="annotation_annotated_at",
            ),
        ),
    ]
