# Generated by Django 3.2.14 on 2023-11-09 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0047_alter_annotation_annotated_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together={("task", "completed_by")},
        ),
    ]
