# Generated by Django 3.2.14 on 2026-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_alter_annotation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=255)),
                ('org_id', models.IntegerField()),
                ('result', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('stat_type', 'org_id')},
            },
        ),
    ]
