# Generated by Django 3.2.23 on 2024-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0048_alter_annotation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="version_updated_at",
            field=models.DateTimeField(
                default="2000-01-01T00:00:00Z",
                verbose_name="annotation_version_updated_at",
            ),
        ),
    ]
