# Generated by Django 3.2.14 on 2026-09-02 09:46, hand-edited to use
# AddIndexConcurrently -- a plain AddIndex runs `CREATE INDEX` inside the
# migration's transaction, which takes an ACCESS EXCLUSIVE lock on the table
# for the duration of the build. On production-sized Task/Annotation tables
# that would block reads and writes (i.e. annotation work) for however long
# the index build takes. CONCURRENTLY avoids that lock at the cost of not
# being usable inside a transaction, hence atomic = False below.
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('tasks', '0048_alter_annotation_unique_together'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='annotation',
            index=models.Index(fields=['annotation_type', 'annotation_status'], name='tasks_annot_annotat_fed312_idx'),
        ),
        AddIndexConcurrently(
            model_name='annotation',
            index=models.Index(fields=['completed_by', 'annotation_type'], name='tasks_annot_complet_7720b7_idx'),
        ),
        AddIndexConcurrently(
            model_name='annotation',
            index=models.Index(fields=['task', 'annotation_type'], name='tasks_annot_task_id_96354b_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['project_id', 'task_status'], name='tasks_task_project_065ab3_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['project_id', 'review_user'], name='tasks_task_project_4cadff_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['project_id', 'super_check_user'], name='tasks_task_project_51cac9_idx'),
        ),
    ]
