# Generated by Django 3.2.23 on 2024-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0049_annotation_version_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="version_updated_at",
            field=models.DateTimeField(
                default="2000-01-01T00:00:00.000001Z",
                verbose_name="annotation_version_updated_at",
            ),
        ),
    ]
