# Generated by Django 3.2.12 on 2022-02-09 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_has_accepted_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="invite_accepted",
        ),
    ]
