# Generated by Django 4.0.1 on 2022-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_organization_id_user_organization"),
        ("users", "0006_alter_user_lang_id"),
    ]

    operations = []
