# Generated by Django 3.1.14 on 2022-03-24 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_auto_20220319_0907"),
        ("users", "0008_auto_20220317_0924"),
    ]

    operations = []
