# Generated by Django 3.1.14 on 2022-04-29 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_auto_20220413_0935"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="maximum_annotations_per_day",
        ),
    ]
