# Generated by Django 3.1.14 on 2022-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_auto_20220502_1329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="language",
        ),
    ]
