# Generated by Django 4.0.4 on 2022-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Annotator'), (2, 'Workspace Manager'), (3, 'Organization Owner'), (4, 'Reviewer'), (5, 'Admin')], default=1),
        ),
    ]
