# Generated by Django 3.2.14 on 2022-10-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_auto_20220929_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="participation_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Full-Time"), (2, "Part-Time"), (3, "N/A")],
                default=1,
                help_text="Indicates the type of participation of user.",
            ),
        ),
    ]
