# Generated by Django 3.2.14 on 2022-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20220930_0451'),
        ('users', '0020_user_participation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(null=True, related_name='organization_users', to='organizations.Organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Annotator'), (2, 'Reviewer'), (3, 'Workspace Manager'), (4, 'Organization Owner'), (5, 'Admin')], default=1),
        ),
    ]
