# Generated by Django 3.2.13 on 2022-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220629_1425'),
        ('users', '0020_alter_user_id'),
    ]

    operations = [
    ]
