# Generated by Django 3.2.14 on 2023-03-06 07:46

from django.db import migrations
from users.models import User


def change_user_email_to_lowercase(apps, schema_editor):
    all_users = User.objects.all()
    users_list = []
    for user in all_users:
        email = user.email
        email = email.lower()
        setattr(user, "email", email)
        users_list.append(user)
    User.objects.bulk_update(users_list, ["email"], 512)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_participation_type"),
    ]

    operations = [
        migrations.RunPython(change_user_email_to_lowercase),
    ]
