# Generated by Django 3.2.14 on 2022-11-30 13:29

from django.db import migrations

def copy_org_relationships(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.organizations.add(user.organization)
        user.save()

def restructure_user_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.role in [2, 3]:
            user.role = user.role + 1
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20221124_1042'),
    ]

    operations = [
        migrations.RunPython(copy_org_relationships),
        migrations.RunPython(restructure_user_roles),
    ]
