# Generated by Django 3.2.14 on 2022-11-30 13:29

from django.db import migrations
from users.models import User


def restructure_user_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.role in [2, 3]:
            user.role = user.role + 1
            user.save()


def change_user_email_to_lowercase(apps, schema_editor):
    all_users = User.objects.all()
    users_list = []
    for user in all_users:
        email = user.email
        email = email.lower()
        setattr(user, "email", email)
        users_list.append(user)
    User.objects.bulk_update(users_list, ["email"], 512)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_auto_20221124_1042"),
    ]

    operations = [
        migrations.RunPython(restructure_user_roles),
        migrations.RunPython(change_user_email_to_lowercase),
    ]
