# Generated by Django 3.2.14 on 2023-03-13 08:53

from django.db import migrations

def restructure_user_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.role in [3, 4]:
            user.role = user.role + 1
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(restructure_user_roles),
    ]
