# Generated by Django 3.2.14 on 2023-03-16 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_user_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="email_org_unique",
        ),
    ]
