# Generated by Django 3.2.14 on 2023-03-21 13:31

from django.db import migrations
from projects.models import Project
from users.models import User


def change_annotatator_added_as_project_reviewer_to_reviewer(apps, schema_editor):
    projects = Project.objects.all()
    users_list = []
    for project in projects:
        for reviewer in project.annotation_reviewers.all():
            if reviewer.role == User.ANNOTATOR:
                setattr(reviewer, "role", User.REVIEWER)
                users_list.append(reviewer)

    User.objects.bulk_update(users_list, ["role"], 512)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_remove_user_email_org_unique"),
    ]

    operations = [
        migrations.RunPython(change_annotatator_added_as_project_reviewer_to_reviewer),
    ]
