# Generated by Django 3.2.14 on 2023-07-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_user_participation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="participation_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Full-Time"),
                    (2, "Part-Time"),
                    (3, "N/A"),
                    (4, "Contract Basis"),
                ],
                default=1,
                help_text="Indicates the type of participation of user.",
            ),
        ),
    ]
