# Generated by Django 3.2.14 on 2023-03-28 07:14

from django.db import migrations
from users.models import User


def change_users_having_superuser_status_to_admin_role(apps, schema_editor):
    users = User.objects.all()
    users_list = []
    for user in users:
        if user.is_superuser:
            setattr(user, "role", User.ADMIN)
            users_list.append(user)

    User.objects.bulk_update(users_list, ["role"], 512)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_change_annotators_added_as_reviewer_to_reviewer"),
    ]

    operations = [
        migrations.RunPython(change_users_having_superuser_status_to_admin_role),
    ]
