# Generated by Django 3.2.14 on 2023-08-09 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("organizations", "0008_auto_20220930_0451"),
        ("workspaces", "0014_workspace_public_analytics"),
        ("users", "0027_alter_user_participation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPeriodicTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "schedule",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Daily"), (2, "Weekly"), (3, "Monthly")],
                        help_text="Schedule of the task.",
                        verbose_name="schedule",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        help_text="Project type of the task.",
                        max_length=256,
                        verbose_name="project_type",
                    ),
                ),
                (
                    "report_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Organization Level"), (2, "Workspace Level")],
                        help_text="Report level of the task.",
                        verbose_name="report_level",
                    ),
                ),
                (
                    "celery_task",
                    models.OneToOneField(
                        help_text="Celery Beat Task for the user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization for which the reports will be generated.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User for which the task is created.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workspace for which the reports will be generated.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
        ),
    ]
