# Generated by Django 3.2.14 on 2023-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_customperiodictask"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prefer_cl_ui",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether user prefers Chitralekha UI for audio transcription tasks or not.",
                verbose_name="prefer_cl_ui",
            ),
        ),
    ]
