# Generated by Django 3.2.14 on 2023-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_prefer_cl_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperiodictask',
            name='notification_limit',
            field=models.BigIntegerField(default=100),
        ),
    ]
