# Generated by Django 3.2.14 on 2023-11-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_user_prefer_cl_ui"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="profile_photo"
            ),
        ),
    ]
