# Generated by Django 3.2.14 on 2023-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_customperiodictask_notification_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customperiodictask',
            name='notification_limit',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_limit',
            field=models.BigIntegerField(default=100),
        ),
    ]
