# Generated by Django 3.2.14 on 2023-12-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_limit",
            field=models.BigIntegerField(
                default=100,
                help_text="Indicates the number of maximum notifications a user will receive.",
                null=True,
            ),
        ),
    ]
