# Generated by Django 3.2.14 on 2023-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date_of_birth"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="guest_user",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Indicates whether the user is a guest user.",
                verbose_name="guest_user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Pin Code"),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=255, verbose_name="state"),
        ),
    ]
