# Generated by Django 3.2.23 on 2024-01-22 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_alter_user_profile_photo"),
    ]

    operations = []
