# Generated by Django 3.2.14 on 2024-01-23 03:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_auto_20240122_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.CharField(
                blank=True,
                help_text="Indicates the age of user",
                max_length=3,
                verbose_name="age",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="qualification",
            field=models.TextField(
                blank=True,
                help_text="Indicates the qualification /designation of user",
                max_length=255,
                verbose_name="qualification",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, default=None, max_length=128, verbose_name="password"
            ),
        ),
    ]
