# Generated by Django 3.2.14 on 2024-01-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_user_guest_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, default=None, max_length=128, verbose_name="password"
            ),
        ),
    ]
