# Generated by Django 3.2.14 on 2024-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_auto_20240123_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_limit",
            field=models.BigIntegerField(
                default=100,
                help_text="Indicates the number of maximum notifications a user will receive.",
                null=True,
            ),
        ),
    ]
