# Generated by Django 3.2.14 on 2025-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_approved_by_user_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace_prefered',
            field=models.JSONField(blank=True, default=dict, help_text='Indicates the preferred workspace of the user', null=True, verbose_name='workspace_prefered'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates whether user is approved by the admin or not.', verbose_name='is_approved'),
        ),
    ]
