# Generated by Django 3.2.14 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace_prefered',
            field=models.JSONField(blank=True, default=dict, help_text='Indicates the preferred workspace of the user', null=True, verbose_name='workspace_prefered'),
        ),
    ]
